# Generated by Django 2.0.3 on 2018-03-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('url', models.URLField(blank=True, null=True)),
                ('pic', models.ImageField(upload_to='resume/')),
                ('position', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=40)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('body', models.TextField()),
            ],
        ),
    ]
