# Generated by Django 2.0.3 on 2018-03-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180329_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
