# Generated by Django 2.0.3 on 2018-03-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180329_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='slug',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sub',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
