# Generated by Django 2.0.3 on 2018-04-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180329_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='cert/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='project/')),
            ],
        ),
    ]
