# Generated by Django 2.0.3 on 2018-04-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cert_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
